#!/bin/bash

# Script found at https://askubuntu.com/a/518092 and modified by me.
# This script extracts compressed files of various formats.
# Usage: extract FILENAME
# Default destination directory is the current working directory.
# Default destination directory can be changed in the prompt that follows after pressing the enter key.

# config
DEFAULT_TARGET="."

SCRIPTNAME="${0##*/}"

err() {
    printf >&2 "$SCRIPTNAME: $*\n"
    exit 1
}

ARC="$1"
[[ -f $ARC ]] || err $"'$ARC' does not exist"
ARC="$(readlink -f "$ARC")"

read -p "Extract to [default: $DEFAULT_TARGET]: " TARGET
[[ -z $TARGET ]] &&\
    TARGET="$DEFAULT_TARGET"
[[ -d $TARGET ]] || err $"Directory '$TARGET' does not exist"
[[ -w $TARGET ]] || err $"Permission denied: '$TARGET' is not writable"

cd "$TARGET"
case "$ARC" in
    *.tar.bz2)   tar xjf "$ARC"     ;;
    *.tar.gz)    tar xzf "$ARC"     ;;
    *.tar.xz)    tar xf "$ARC"     ;;
    *.bz2)       bunzip2 --keep "$ARC"     ;;
    *.rar)       unrar x "$ARC"     ;;
    *.gz)        gunzip --keep "$ARC"      ;;
    *.tar)       tar xf "$ARC"      ;;
    *.tbz2)      tar xjf "$ARC"     ;;
    *.tgz)       tar xzf "$ARC"     ;;
    *.zip)       unzip "$ARC"       ;;
    *.Z)         uncompress "$ARC"  ;;
    *.7z)        7z x "$ARC"        ;;
    *.tar.zst)   tar -I zstd -xf "$ARC"        ;;
    *)           echo "'$ARC' cannot be extracted by $SCRIPTNAME" ;;
esac
